name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - name: Get the source
        uses: actions/checkout@v4
      - name: Restore the Dependencies
        run: npm ci
      - name: Build
        run: npm run all